[package]
name = "ftpd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libunftp = "0.18.6"
unftp-sbe-fs = "0.2"
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
jni = "0.19"
log = "0.4.17"
an_logger = "0.1.0"
